export default function DisclaimerPage() {
  return (
    <div className="page-container fade-in" style={{ maxWidth: 800 }}>
      <div className="page-header">
        <h1>Legal Disclaimer</h1>
        <p>
          Important information about the use of this platform and its limitations.
        </p>
      </div>

      <div style={{
        background: 'var(--accent-bg)', borderRadius: 16,
        padding: '20px 24px', marginBottom: 32,
        border: '1px solid rgba(217, 119, 6, 0.2)',
      }}>
        <p style={{ fontSize: 14, color: '#92400E', fontWeight: 600 }}>
          Please read this disclaimer carefully before using the SETU platform.
        </p>
      </div>

      {[
        {
          title: '1. General Information Only',
          content: 'The information provided on this platform is for general informational and educational purposes only. It is not intended to be, and should not be construed as, legal advice. The content is provided "as is" and does not create any attorney-client relationship between the user and the platform.'
        },
        {
          title: '2. Not a Substitute for Professional Legal Advice',
          content: 'SETU is not a substitute for professional legal advice from a qualified and licensed lawyer. For specific legal issues, disputes, or concerns, you should always consult with a qualified legal professional who can provide advice tailored to your specific situation and the applicable laws in your jurisdiction.'
        },
        {
          title: '3. Accuracy of Information',
          content: 'While we strive to provide accurate and up-to-date information about Indian laws, legal procedures, and government schemes, we do not warrant or guarantee the accuracy, completeness, or timeliness of the information presented. Laws and regulations are subject to change, and the information on this platform may not reflect the most current legal developments.'
        },
        {
          title: '4. Document Generator Disclaimer',
          content: 'The legal documents generated by this platform (including but not limited to FIR drafts, RTI applications, legal notices, consumer complaints, and rent notices) are templates for reference purposes only. These documents:\n\n• Are not certified or attested legal documents\n• May not meet all legal requirements in your specific case\n• Should be reviewed by a qualified lawyer before submission\n• May require modifications based on your state\'s specific laws and regulations\n• Do not guarantee any specific legal outcome'
        },
        {
          title: '5. Government Scheme Information',
          content: 'Information about government schemes, eligibility criteria, benefits, and application procedures is compiled from publicly available sources. Scheme details, eligibility criteria, and benefits are subject to change by the respective government authorities. Always verify current details on the official government websites linked from this platform.'
        },
        {
          title: '6. No Liability',
          content: 'Under no circumstances shall the creators, developers, or contributors of this platform be liable for any direct, indirect, incidental, consequential, special, or exemplary damages arising out of or in connection with the use of this platform, including but not limited to:\n\n• Any errors or omissions in the content\n• Any action taken or not taken based on the information provided\n• Any loss or damage incurred as a result of using generated documents\n• Any reliance on government scheme information\n• Technical issues, data loss, or service interruptions'
        },
        {
          title: '7. External Links',
          content: 'This platform contains links to external websites, including government portals and official websites. These links are provided for convenience only. We do not control these external websites and are not responsible for their content, accuracy, or availability.'
        },
        {
          title: '8. Academic Project',
          content: 'SETU is developed as a final-year college project for educational and demonstration purposes. It is not a commercial legal service. The platform does not collect, store, or share any personal information entered in the document generator forms beyond what is necessary for generating the requested documents.'
        },
        {
          title: '9. Laws Referenced',
          content: 'This platform references various Indian laws including but not limited to:\n\n• The Constitution of India\n• Consumer Protection Act, 2019\n• Information Technology Act, 2000\n• Bharatiya Nagarik Suraksha Sanhita (BNSS), 2023\n• Bharatiya Nyaya Sanhita (BNS), 2023\n• Right to Information Act, 2005\n• Real Estate (Regulation and Development) Act, 2016\n• Labour Codes (2019-2020)\n• Various State-specific Rent Control Acts\n\nAll legal references are based on publicly available versions of these laws.'
        },
        {
          title: '10. Contact for Corrections',
          content: 'If you find any inaccuracy in the information presented on this platform, please report it so we can make corrections. Despite our best efforts, errors may exist in the content.'
        },
      ].map((section, i) => (
        <section key={i} style={{ marginBottom: 24 }}>
          <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 10, color: 'var(--text)' }}>{section.title}</h2>
          <div className="card">
            {section.content.split('\n\n').map((para, j) => (
              <p key={j} style={{
                fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8,
                marginBottom: j < section.content.split('\n\n').length - 1 ? 12 : 0,
                whiteSpace: para.startsWith('•') ? 'pre-line' : 'normal',
              }}>{para}</p>
            ))}
          </div>
        </section>
      ))}

      {/* Last Updated */}
      <div style={{
        textAlign: 'center', padding: '24px',
        borderTop: '1px solid var(--border)', marginTop: 20,
      }}>
        <p style={{ fontSize: 12, color: 'var(--text-muted)' }}>
          Last Updated: March 2026 | SETU – Legal Awareness & Document Assistance Platform
        </p>
      </div>
    </div>
  );
}
