import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    nav: {
      home: 'Home',
      legalKnowledge: 'Legal Knowledge',
      legalProcedures: 'Legal Procedures',
      govSchemes: 'Gov Schemes',
      docGen: 'Document Generator',
      about: 'About',
      disclaimer: 'Legal Disclaimer',
      legalAwareness: 'LEGAL AWARENESS',
    },
    common: {
      english: 'English',
      hindi: 'हिंदी',
    },
    footer: {
      description: 'Legal awareness and document assistance platform making justice accessible for every Indian citizen.',
      platform: 'Platform',
      legal: 'Legal',
      aboutSetu: 'About SETU',
      emergencyNumbers: 'Emergency Numbers',
      copyright: '© 2026 SETU – Legal Awareness & Document Assistance Platform. This platform provides legal information for educational purposes only. It is not a substitute for professional legal advice. Created as a college project.',
      police: 'Police Emergency',
      cyber: 'Cyber Fraud Helpline',
      women: 'Women Helpline',
      child: 'Child Helpline',
      govSchemes: 'Government Schemes',
    },
    fab: {
      chat: 'AI Agent Chat',
    },
    pages: {
      legalKnowledgeTitle: 'Legal Knowledge Hub',
      legalKnowledgeDesc: 'Indian laws explained in simple language. Each law page includes an overview, key sections, real-world examples, and practical use cases.',
      legalKnowledgeTip: 'Tip:',
      legalKnowledgeTipText: 'Click on any law category below to read a detailed explanation with key sections, examples, and how it applies to everyday situations.',
      readFullDetails: 'Read Full Details →',
      legalProceduresTitle: 'Legal Procedure Guide',
      legalProceduresDesc: 'Step-by-step guides for common legal procedures in India. Each guide includes purpose, required documents, steps, fees, timeline, and official links.',
      legalProceduresNote: 'Note:',
      legalProceduresNoteText: 'These guides are based on the latest Indian laws (BNS/BNSS 2023). Always verify requirements with the concerned authority as they may vary by state.',
      viewCompleteGuide: 'View Complete Guide →',
      schemesTitle: 'Government Scheme Explorer',
      schemesDesc: 'Search and explore Indian government schemes. Check eligibility, benefits, required documents, and access official websites.',
      schemesSearchPlaceholder: 'Search schemes by name, eligibility, or benefits...',
      showing: 'Showing',
      schemes: 'scheme(s)',
      noResults: 'No results',
      noSchemesFound: 'No schemes found',
      tryDifferent: 'Try a different search term or category',
      eligibility: 'Eligibility:',
      requiredDocuments: 'Required Documents',
      hideDetails: '▲ Hide Details',
      showDetails: '▼ Required Documents',
      visitOfficial: 'Visit Official Website',
      all: 'All',
      docTitle: 'Legal Document Generator',
      docDesc: 'Generate formatted legal documents by filling simple forms. Preview the document and download as PDF.',
      docDisclaimerHead: 'Disclaimer:',
      docDisclaimerText: 'These documents are generated for informational and educational purposes only. Please consult a qualified lawyer before using any legal document in official proceedings.',
      selectDocType: 'Select Document Type',
      generate: 'Generate →',
      backToDocTypes: '← Back to Document Types',
      previewDocument: 'Preview Document',
      reset: 'Reset',
      backToForm: '← Back to Form',
      edit: 'Edit',
      downloadPdf: 'Download PDF',
      saving: 'Saving...',
      previewLabel: 'Preview',
      aboutTitle: 'About SETU',
      aboutSubtitle: 'Understanding the platform, its purpose, and the team behind it.',
      disclaimerTitle: 'Legal Disclaimer',
      disclaimerSubtitle: 'Important information about the use of this platform and its limitations.',
    },
  },
  hi: {
    nav: {
      home: 'होम',
      legalKnowledge: 'कानूनी जानकारी',
      legalProcedures: 'कानूनी प्रक्रियाएँ',
      govSchemes: 'सरकारी योजनाएँ',
      docGen: 'दस्तावेज़ जनरेटर',
      about: 'परिचय',
      disclaimer: 'कानूनी अस्वीकरण',
      legalAwareness: 'कानूनी जागरूकता',
    },
    common: {
      english: 'English',
      hindi: 'हिंदी',
    },
    footer: {
      description: 'कानूनी जागरूकता और दस्तावेज़ सहायता प्लेटफ़ॉर्म जो हर भारतीय नागरिक के लिए न्याय को सुलभ बनाता है।',
      platform: 'प्लेटफ़ॉर्म',
      legal: 'कानूनी',
      aboutSetu: 'SETU के बारे में',
      emergencyNumbers: 'आपातकालीन नंबर',
      copyright: '© 2026 SETU – कानूनी जागरूकता एवं दस्तावेज़ सहायता प्लेटफ़ॉर्म। यह प्लेटफ़ॉर्म केवल शैक्षणिक जानकारी के लिए है और पेशेवर कानूनी सलाह का विकल्प नहीं है।',
      police: 'पुलिस आपातकाल',
      cyber: 'साइबर फ्रॉड हेल्पलाइन',
      women: 'महिला हेल्पलाइन',
      child: 'चाइल्ड हेल्पलाइन',
      govSchemes: 'सरकारी योजनाएँ',
    },
    fab: {
      chat: 'AI एजेंट चैट',
    },
    pages: {
      legalKnowledgeTitle: 'कानूनी जानकारी केंद्र',
      legalKnowledgeDesc: 'भारतीय कानून सरल भाषा में। हर पेज में सारांश, मुख्य धाराएँ, उदाहरण और उपयोग शामिल हैं।',
      legalKnowledgeTip: 'सुझाव:',
      legalKnowledgeTipText: 'नीचे दिए किसी भी कानून पर क्लिक करें और विस्तृत जानकारी पढ़ें।',
      readFullDetails: 'पूरी जानकारी पढ़ें →',
      legalProceduresTitle: 'कानूनी प्रक्रिया गाइड',
      legalProceduresDesc: 'भारत की सामान्य कानूनी प्रक्रियाओं के चरण-दर-चरण गाइड।',
      legalProceduresNote: 'नोट:',
      legalProceduresNoteText: 'ये गाइड नवीनतम भारतीय कानूनों (BNS/BNSS 2023) पर आधारित हैं। राज्य के अनुसार अंतर हो सकता है।',
      viewCompleteGuide: 'पूरा गाइड देखें →',
      schemesTitle: 'सरकारी योजना एक्सप्लोरर',
      schemesDesc: 'भारतीय सरकारी योजनाएँ खोजें, पात्रता और लाभ देखें।',
      schemesSearchPlaceholder: 'योजना नाम, पात्रता या लाभ से खोजें...',
      showing: 'दिखाई जा रही',
      schemes: 'योजना(एँ)',
      noResults: 'कोई परिणाम नहीं',
      noSchemesFound: 'कोई योजना नहीं मिली',
      tryDifferent: 'अलग खोज शब्द या श्रेणी आज़माएँ',
      eligibility: 'पात्रता:',
      requiredDocuments: 'आवश्यक दस्तावेज़',
      hideDetails: '▲ विवरण छुपाएँ',
      showDetails: '▼ आवश्यक दस्तावेज़',
      visitOfficial: 'आधिकारिक वेबसाइट देखें',
      all: 'सभी',
      docTitle: 'कानूनी दस्तावेज़ जनरेटर',
      docDesc: 'सरल फॉर्म भरकर PDF में कानूनी दस्तावेज़ बनाएँ।',
      docDisclaimerHead: 'अस्वीकरण:',
      docDisclaimerText: 'ये दस्तावेज़ केवल जानकारी हेतु हैं। आधिकारिक उपयोग से पहले वकील से सलाह लें।',
      selectDocType: 'दस्तावेज़ प्रकार चुनें',
      generate: 'बनाएँ →',
      backToDocTypes: '← दस्तावेज़ प्रकार पर वापस',
      previewDocument: 'पूर्वावलोकन देखें',
      reset: 'रीसेट',
      backToForm: '← फॉर्म पर वापस',
      edit: 'संपादित करें',
      downloadPdf: 'PDF डाउनलोड करें',
      saving: 'सेव हो रहा है...',
      previewLabel: 'पूर्वावलोकन',
      aboutTitle: 'SETU के बारे में',
      aboutSubtitle: 'प्लेटफ़ॉर्म, उद्देश्य और टीम की जानकारी।',
      disclaimerTitle: 'कानूनी अस्वीकरण',
      disclaimerSubtitle: 'इस प्लेटफ़ॉर्म के उपयोग और सीमाओं से जुड़ी महत्वपूर्ण जानकारी।',
    },
  },
  bho: {
    nav: {
      home: 'घर',
      legalKnowledge: 'कानूनी जानकारी',
      legalProcedures: 'कानूनी प्रक्रिया',
      govSchemes: 'सरकारी योजना',
      docGen: 'दस्तावेज बनाव',
      about: 'परिचय',
      disclaimer: 'कानूनी अस्वीकरण',
      legalAwareness: 'कानूनी जागरूकता',
    },
    common: { english: 'English', hindi: 'हिंदी' },
    footer: {
      description: 'कानूनी जानकारी आ दस्तावेज मदद वाला प्लेटफॉर्म, जे न्याय सबके लगे ले आवेला।',
      platform: 'प्लेटफॉर्म',
      legal: 'कानूनी',
      aboutSetu: 'SETU के बारे में',
      emergencyNumbers: 'आपातकालीन नंबर',
      copyright: '© 2026 SETU – ई प्लेटफॉर्म खाली जानकारी खातिर बा, कानूनी सलाह खातिर वकील से बात करीं।',
      police: 'पुलिस',
      cyber: 'साइबर हेल्पलाइन',
      women: 'महिला हेल्पलाइन',
      child: 'बाल हेल्पलाइन',
      govSchemes: 'सरकारी योजना',
    },
    fab: { chat: 'AI एजेंट चैट' },
    pages: {
      legalKnowledgeTitle: 'कानूनी जानकारी केंद्र',
      legalKnowledgeDesc: 'भारतीय कानून सभे के आसान भाषा में समझावल गइल बा।',
      legalKnowledgeTip: 'सुझाव:',
      legalKnowledgeTipText: 'नीचे से कोई कानून चुनीं आ पूरा जानकारी पढ़ीं।',
      readFullDetails: 'पूरा जानकारी पढ़ीं →',
      legalProceduresTitle: 'कानूनी प्रक्रिया गाइड',
      legalProceduresDesc: 'भारत में आम कानूनी प्रक्रिया के स्टेप-बाय-स्टेप गाइड।',
      legalProceduresNote: 'नोट:',
      legalProceduresNoteText: 'राज्य के हिसाब से नियम में फर्क हो सकेला।',
      viewCompleteGuide: 'पूरा गाइड देखीं →',
      schemesTitle: 'सरकारी योजना खोज',
      schemesDesc: 'योजना खोजीं, पात्रता देखीं, लाभ समझीं।',
      schemesSearchPlaceholder: 'योजना, पात्रता, लाभ से खोजीं...',
      showing: 'दिखावल जा रहल बा',
      schemes: 'योजना',
      noResults: 'कवनो परिणाम नाहीं',
      noSchemesFound: 'कवनो योजना ना मिलल',
      tryDifferent: 'अलग खोज शब्द लिहीं',
      eligibility: 'पात्रता:',
      requiredDocuments: 'जरूरी कागज',
      hideDetails: '▲ विवरण छुपाईं',
      showDetails: '▼ जरूरी कागज',
      visitOfficial: 'ऑफिशियल वेबसाइट खोलीं',
      all: 'सब',
      docTitle: 'कानूनी दस्तावेज जनरेटर',
      docDesc: 'आसान फॉर्म भर के PDF बनाईं।',
      docDisclaimerHead: 'अस्वीकरण:',
      docDisclaimerText: 'दस्तावेज इस्तेमाल से पहिले वकील से सलाह जरूर लीं।',
      selectDocType: 'दस्तावेज चुनीं',
      generate: 'बनाईं →',
      backToDocTypes: '← वापस',
      previewDocument: 'प्रीव्यू देखीं',
      reset: 'रीसेट',
      backToForm: '← फॉर्म पर वापस',
      edit: 'संपादन',
      downloadPdf: 'PDF डाउनलोड',
      saving: 'सेव हो रहल बा...',
      previewLabel: 'प्रीव्यू',
      aboutTitle: 'SETU के बारे में',
      aboutSubtitle: 'प्लेटफॉर्म, उद्देश्य आ टीम के जानकारी।',
      disclaimerTitle: 'कानूनी अस्वीकरण',
      disclaimerSubtitle: 'ई प्लेटफॉर्म के इस्तेमाल से जुड़ल जरूरी जानकारी।',
    },
  },
  bn: {
    nav: {
      home: 'হোম',
      legalKnowledge: 'আইনি জ্ঞান',
      legalProcedures: 'আইনি প্রক্রিয়া',
      govSchemes: 'সরকারি স্কিম',
      docGen: 'ডকুমেন্ট জেনারেটর',
      about: 'পরিচিতি',
      disclaimer: 'আইনি ডিসক্লেমার',
      legalAwareness: 'আইনি সচেতনতা',
    },
    common: { english: 'English', hindi: 'हिंदी' },
    footer: {
      description: 'আইনি সচেতনতা ও ডকুমেন্ট সহায়তা প্ল্যাটফর্ম, যা নাগরিকদের জন্য ন্যায়কে সহজ করে।',
      platform: 'প্ল্যাটফর্ম',
      legal: 'আইনি',
      aboutSetu: 'SETU সম্পর্কে',
      emergencyNumbers: 'জরুরি নম্বর',
      copyright: '© 2026 SETU – এই প্ল্যাটফর্ম কেবল শিক্ষামূলক তথ্যের জন্য।',
      police: 'পুলিশ জরুরি',
      cyber: 'সাইবার হেল্পলাইন',
      women: 'মহিলা হেল্পলাইন',
      child: 'শিশু হেল্পলাইন',
      govSchemes: 'সরকারি স্কিম',
    },
    fab: { chat: 'AI এজেন্ট চ্যাট' },
    pages: {
      legalKnowledgeTitle: 'আইনি জ্ঞান কেন্দ্র',
      legalKnowledgeDesc: 'ভারতীয় আইন সহজ ভাষায় ব্যাখ্যা করা হয়েছে।',
      legalKnowledgeTip: 'টিপস:',
      legalKnowledgeTipText: 'নিচে যেকোনো আইন নির্বাচন করে বিস্তারিত পড়ুন।',
      readFullDetails: 'বিস্তারিত পড়ুন →',
      legalProceduresTitle: 'আইনি প্রক্রিয়া গাইড',
      legalProceduresDesc: 'সাধারণ আইনি প্রক্রিয়ার ধাপে ধাপে গাইড।',
      legalProceduresNote: 'নোট:',
      legalProceduresNoteText: 'রাজ্যভেদে কিছু নিয়ম আলাদা হতে পারে।',
      viewCompleteGuide: 'পূর্ণ গাইড দেখুন →',
      schemesTitle: 'সরকারি স্কিম এক্সপ্লোরার',
      schemesDesc: 'স্কিম খুঁজুন, যোগ্যতা ও সুবিধা দেখুন।',
      schemesSearchPlaceholder: 'নাম, যোগ্যতা বা সুবিধা দিয়ে সার্চ করুন...',
      showing: 'দেখানো হচ্ছে',
      schemes: 'স্কিম',
      noResults: 'কোন ফলাফল নেই',
      noSchemesFound: 'কোনো স্কিম পাওয়া যায়নি',
      tryDifferent: 'অন্য সার্চ শব্দ ব্যবহার করুন',
      eligibility: 'যোগ্যতা:',
      requiredDocuments: 'প্রয়োজনীয় কাগজপত্র',
      hideDetails: '▲ বিস্তারিত লুকান',
      showDetails: '▼ প্রয়োজনীয় কাগজপত্র',
      visitOfficial: 'অফিশিয়াল ওয়েবসাইট দেখুন',
      all: 'সব',
      docTitle: 'আইনি ডকুমেন্ট জেনারেটর',
      docDesc: 'সহজ ফর্ম পূরণ করে PDF ডকুমেন্ট তৈরি করুন।',
      docDisclaimerHead: 'ডিসক্লেমার:',
      docDisclaimerText: 'ব্যবহারের আগে আইনজীবীর সাথে পরামর্শ করুন।',
      selectDocType: 'ডকুমেন্ট টাইপ নির্বাচন করুন',
      generate: 'তৈরি করুন →',
      backToDocTypes: '← ফিরে যান',
      previewDocument: 'প্রিভিউ দেখুন',
      reset: 'রিসেট',
      backToForm: '← ফর্মে ফিরে যান',
      edit: 'এডিট',
      downloadPdf: 'PDF ডাউনলোড',
      saving: 'সেভ হচ্ছে...',
      previewLabel: 'প্রিভিউ',
      aboutTitle: 'SETU সম্পর্কে',
      aboutSubtitle: 'প্ল্যাটফর্ম, উদ্দেশ্য ও টিম সম্পর্কে তথ্য।',
      disclaimerTitle: 'আইনি ডিসক্লেমার',
      disclaimerSubtitle: 'এই প্ল্যাটফর্ম ব্যবহারের গুরুত্বপূর্ণ তথ্য।',
    },
  },
  hinglish: {
    nav: {
      home: 'Home',
      legalKnowledge: 'Legal Gyaan',
      legalProcedures: 'Legal Process',
      govSchemes: 'Govt Schemes',
      docGen: 'Document Generator',
      about: 'About',
      disclaimer: 'Legal Disclaimer',
      legalAwareness: 'LEGAL AWARENESS',
    },
    common: { english: 'English', hindi: 'हिंदी' },
    footer: {
      description: 'Legal awareness aur document help platform jo justice ko easy banata hai.',
      platform: 'Platform',
      legal: 'Legal',
      aboutSetu: 'About SETU',
      emergencyNumbers: 'Emergency Numbers',
      copyright: '© 2026 SETU – Ye platform sirf educational purpose ke liye hai.',
      police: 'Police Emergency',
      cyber: 'Cyber Helpline',
      women: 'Women Helpline',
      child: 'Child Helpline',
      govSchemes: 'Government Schemes',
    },
    fab: { chat: 'AI Agent Chat' },
    pages: {
      legalKnowledgeTitle: 'Legal Knowledge Hub',
      legalKnowledgeDesc: 'Indian laws simple language me explained.',
      legalKnowledgeTip: 'Tip:',
      legalKnowledgeTipText: 'Kisi bhi law pe click karo aur full details dekho.',
      readFullDetails: 'Read Full Details →',
      legalProceduresTitle: 'Legal Procedure Guide',
      legalProceduresDesc: 'Common legal procedures ka step-by-step guide.',
      legalProceduresNote: 'Note:',
      legalProceduresNoteText: 'State ke hisab se rules thode change ho sakte hain.',
      viewCompleteGuide: 'View Complete Guide →',
      schemesTitle: 'Government Scheme Explorer',
      schemesDesc: 'Schemes search karo, eligibility aur benefits check karo.',
      schemesSearchPlaceholder: 'Scheme name, eligibility ya benefits se search karo...',
      showing: 'Showing',
      schemes: 'scheme(s)',
      noResults: 'No results',
      noSchemesFound: 'No schemes found',
      tryDifferent: 'Different search term try karo',
      eligibility: 'Eligibility:',
      requiredDocuments: 'Required Documents',
      hideDetails: '▲ Hide Details',
      showDetails: '▼ Required Documents',
      visitOfficial: 'Visit Official Website',
      all: 'All',
      docTitle: 'Legal Document Generator',
      docDesc: 'Simple form bhar ke PDF document generate karo.',
      docDisclaimerHead: 'Disclaimer:',
      docDisclaimerText: 'Use karne se pehle lawyer se verify zaroor karein.',
      selectDocType: 'Select Document Type',
      generate: 'Generate →',
      backToDocTypes: '← Back',
      previewDocument: 'Preview Document',
      reset: 'Reset',
      backToForm: '← Back to Form',
      edit: 'Edit',
      downloadPdf: 'Download PDF',
      saving: 'Saving...',
      previewLabel: 'Preview',
      aboutTitle: 'About SETU',
      aboutSubtitle: 'Platform, purpose aur team ki details.',
      disclaimerTitle: 'Legal Disclaimer',
      disclaimerSubtitle: 'Platform use karne se pehle important info.',
    },
  },
};

function getByPath(obj, path) {
  return path.split('.').reduce((acc, key) => (acc ? acc[key] : undefined), obj);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const value = useMemo(() => {
    const t = (key) => {
      return getByPath(translations[language], key) ?? getByPath(translations.en, key) ?? key;
    };
    const languages = [
      { code: 'en', label: 'English' },
      { code: 'hi', label: 'हिंदी' },
      { code: 'bho', label: 'भोजपुरी' },
      { code: 'bn', label: 'বাংলা' },
      { code: 'hinglish', label: 'Hinglish' },
    ];
    return { language, setLanguage, t, languages };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
